### ISSUE TITLE
Uninitialized quaternion, assuming identity.

### ISSUE THREAD

**Issue by crankler** [AutoLidarPerception/kitti_ros#24]
你好,谢谢分享, 请问以下问题应该如何解决呢?谢谢!

当我使用这个包时,在rviz中的marker显示warning,并显示Uninitialized quaternion, assuming identity.命令行显示如下:

`[ WARN] [1597234376.998581780]: PoseArray msg received on topic '/kitti/bb_raw' contains unnormalized quaternions. This warning will only be output once but may be true for others; enable DEBUG messages for ros.rviz.quaternions to see more details.
`

**Comment by Durant35** [comment]
功能没异常的话，**[ WARN]**可以忽略...

**Comment by crankler** [comment]
哦哦谢谢大佬的回复!
 同时想咨询下,在kitti集中这种带标签的点云要付现的话大体是什么思路呢?就是不同的物体有不同的标签,显示不同的点云颜色

![00](https://user-images.githubusercontent.com/31907141/90038179-b29eb600-dcf7-11ea-9f5c-e8048f45e142.png)
